version: '3.9'

services:
  mckinseycrudapi:
    container_name: mckinseycrudapi
    image: mckinseycrudapi
    build: .
    ports:
      - "0.0.0.0:8080:80"
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - "0.0.0.0:5432:5432"
    env_file:
      - ".env"
    volumes:
      - /home/data/pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}

